[sop]

[sop.t]
event = "createNode"
node_name = "xform"


[sop.w]
event= "createNode"
node_name = "attribwrangle"

[sop.b]
event= "createNode"
node_name = "blast"

[sop.m]
event= "createNode"
node_name = "merge"

[sop.n]
event= "createNode"
node_name = "null"

[sop.g]
event= "createNode"
node_name = "groupcreate"


[sop.shift_y]
event = "yank"
action = "copy" 


[sop.shift_p]
event = "yank"
action = "paste"

[sop.p]
event ="yank"

[vop]

[vop.b]
event= "createNode"
node_name = "bind"

[lop]

[lop.t]
event= "createNode"
node_name = "xform"

[obj]

[obj.g]
event= "createNode"
node_name = "geo"

[global_]

[global.1]
event = "nodeSwitch"
action = "set"

[global.2]
event = "nodeSwitch"
action = "set"

[global.3]
event = "nodeSwitch"
action = "set"

[global.4]
event = "nodeSwitch"
action = "set"

[global.5]
event = "nodeSwitch"
action = "set"

[global.shift_1]
event = "nodeSwitch"
action = "save"

[global.shift_2]
event = "nodeSwitch"
action = "save"

[global.shift_3]
event = "nodeSwitch"
action = "save"

[global.shift_4]
event = "nodeSwitch"
action = "save"

[global.shift_5]
event = "nodeSwitch"
action = "save"